version: "3"
services:
    backend:
        container_name: bitlinguist
        image:  "lkdubon/bitlinguist:latest"
        restart: on-failure
        build: .
        ports:
            - "3000:3000"
        links:
            - mongo
            - redis
    mongo:
        container_name: mongodb
        image: mongo
        ports:
            - "27017:27017"
    redis:
        container_name: redis
        image: "redis:latest"
        ports:
            - "6379:6379"